# Generated by Django 3.0 on 2019-12-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vin_code')),
            ],
        ),
        migrations.CreateModel(
            name='Vincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('odometr', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('primary_damage', models.CharField(max_length=100)),
                ('secondary_damage', models.CharField(max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Image')),
            ],
        ),
    ]
