# Generated by Django 3.0 on 2019-12-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191205_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Vin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vincode', to='main_app.Vincode'),
        ),
    ]
